apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: demo-app
  labels:
    release: kube-prometheus-stack

spec:
  selector:
    matchLabels:
      app: backend-app

  endpoints:
    - port: http
      path: /metrics
      interval: 10s