apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: demo-app
  labels:
    app: backend-app

spec:
  selector:
    app: backend-app

  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001