apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: demo-app
type: Opaque
data:
  MONGOUSER: YWRtaW4=
  MONGOPASSWORD: YWRtaW5AMTIz
  MONGO_URL: bW9uZ29kYjovL2FkbWluOmFkbWluJTQwMTIzQG1vbmdvLXNlcnZpY2U6MjcwMTcvZGVtbz9hdXRoU291cmNlPWFkbWlu