apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: demo-app
type: Opaque
data:
  MONGOUSER: YWRtaW4=
  MONGOPASSWORD: YWRtaW5AMTIz
  MONGO_URL: bW9uZ29kYjovL2FkbWluOmFkbWluJTQwMTIzQG1vbmdvLTAubW9uZ28taGVhZGxlc3MuZGVtby1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcsbW9uZ28tMS5tb25nby1oZWFkbGVzcy5kZW1vLWFwcC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxtb25nby0yLm1vbmdvLWhlYWRsZXNzLmRlbW8tYXBwLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2RlbW8/cmVwbGljYVNldD1yczAmYXV0aFNvdXJjZT1hZG1pbg==